import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import { Theme } from '@radix-ui/themes';
import { AiFillBug } from "react-icons/ai";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <head>
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/5262/5262375.png" /> 
      </head>
      <body className={inter.variable}>
      <Theme appearance='light' accentColor="teal">
        <NavBar/>
        <main className='p-5'>
          {children}
        </main>
      </Theme>
      </body>
    </html>
  )
}
